server {
    listen 8080;
    server_name _;
    server_tokens off;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /momo-store/;
    }

    location = /momo-store {
        return 301 /momo-store/;
    }

    location /momo-store/ {
        try_files $uri $uri/ /momo-store/index.html;
    }

    location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|map)$ {
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
